[project]
name = "nns"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "clinamen2>=2025.7.1",
    "cuda-toolkit==13.1.1",
    "flax==0.12.8",
    "frozendict>=2.4.7",
    "jax[cuda13-local]==0.11.0",
    "jax-cuda13-pjrt==0.11.0",
    "jax-cuda13-plugin==0.11.0",
    "jaxlib==0.11.0",
    "jaxtyping==0.3.7",
    "matplotlib==3.10.9",
    "matplotlib-inline==0.1.7",
    "netket==3.22.3",
    "numpy==2.3.5",
    "nvidia-cublas==13.6.0.2",
    "nvidia-cuda-cccl==13.3.3.4.1",
    "nvidia-cuda-crt==13.3.73",
    "nvidia-cuda-cupti==13.3.75",
    "nvidia-cuda-nvcc==13.3.73",
    "nvidia-cuda-nvrtc==13.3.33",
    "nvidia-cuda-runtime==13.3.29",
    "nvidia-cudnn-cu13==9.24.0.43",
    "nvidia-cufft==12.3.0.29",
    "nvidia-cusolver==12.2.6.9",
    "nvidia-cusparse==12.8.2.51",
    "nvidia-nccl-cu13==2.30.7",
    "nvidia-nvjitlink==13.3.33",
    "nvidia-nvshmem-cu13==3.7.2",
    "nvidia-nvvm==13.3.73",
    "optax>=0.2.8",
    "optimistix>=0.1.0",
    "pyqt5>=5.15.11",
    "pyside6>=6.11.1",
    "scipy==1.17.0",
    "seaborn>=0.13.2",
    "spglib>=2.7.0",
    "pytest>=9.1.1",
]
